package arcadia

/*
 * @since   Aug. 30, 2017
 *  version Sep.  4, 2017
 * @version Oct. 12, 2017
 * @author  ASAMI, Tomoharu
 */
package object domain {
  val KEY_DOMAIN_OBJECT_ID = 'id
  val KEY_DOMAIN_OBJECT_NAME = 'name
  val KEY_DOMAIN_OBJECT_TITLE = 'title
  val KEY_DOMAIN_OBJECT_CONTENT = 'content
  val KEY_DOMAIN_OBJECT_IMAGE_ICON = 'image_icon
  val KEY_DOMAIN_OBJECT_IMAGE_PRIMARY = 'image_primary
  val PROP_DOMAIN_OBJECT_ID = KEY_DOMAIN_OBJECT_ID.name
  val PROP_DOMAIN_OBJECT_NAME = KEY_DOMAIN_OBJECT_NAME.name
  val PROP_DOMAIN_OBJECT_TITLE = KEY_DOMAIN_OBJECT_TITLE.name
  val PROP_DOMAIN_OBJECT_CONTENT = KEY_DOMAIN_OBJECT_CONTENT.name
  val PROP_DOMAIN_OBJECT_IMAGE_ICON = KEY_DOMAIN_OBJECT_IMAGE_ICON.name
  val PROP_DOMAIN_OBJECT_IMAGE_PRIMARY = KEY_DOMAIN_OBJECT_IMAGE_PRIMARY.name
}
