package arcadia

/*
 * @since   Aug. 30, 2017
 *  version Sep.  4, 2017
 *  version Oct. 18, 2017
 * @version Nov.  5, 2017
 * @author  ASAMI, Tomoharu
 */
package object domain {
  val KEY_DOMAIN_OBJECT_ID = 'id
  val KEY_DOMAIN_OBJECT_NAME = 'name
  val KEY_DOMAIN_OBJECT_TITLE = 'title
  val KEY_DOMAIN_OBJECT_SUBTITLE = 'subtitle
  val KEY_DOMAIN_OBJECT_SUMMARY = 'summary
  val KEY_DOMAIN_OBJECT_CONTENT = 'content
  val KEY_DOMAIN_OBJECT_IMAGE_ICON = 'image_icon
  val KEY_DOMAIN_OBJECT_IMAGE_PRIMARY = 'image_primary
  val KEY_DOMAIN_OBJECT_IMAGE_SECONDARY = 'image_secondary
  val KEY_DOMAIN_OBJECT_PRESENTATION_ID = 'presentation_id
  val KEY_DOMAIN_OBJECT_ENTITYTYPE = 'entitytype
  val KEY_DOMAIN_OBJECT_HREF_BASE = 'href_base
  val PROP_DOMAIN_OBJECT_ID = KEY_DOMAIN_OBJECT_ID.name
  val PROP_DOMAIN_OBJECT_NAME = KEY_DOMAIN_OBJECT_NAME.name
  val PROP_DOMAIN_OBJECT_TITLE = KEY_DOMAIN_OBJECT_TITLE.name
  val PROP_DOMAIN_OBJECT_SUBTITLE = KEY_DOMAIN_OBJECT_SUBTITLE.name
  val PROP_DOMAIN_OBJECT_SUMMARY = KEY_DOMAIN_OBJECT_SUMMARY.name
  val PROP_DOMAIN_OBJECT_CONTENT = KEY_DOMAIN_OBJECT_CONTENT.name
  val PROP_DOMAIN_OBJECT_IMAGE_ICON = KEY_DOMAIN_OBJECT_IMAGE_ICON.name
  val PROP_DOMAIN_OBJECT_IMAGE_PRIMARY = KEY_DOMAIN_OBJECT_IMAGE_PRIMARY.name
  val PROP_DOMAIN_OBJECT_IMAGE_SECONDARY = KEY_DOMAIN_OBJECT_IMAGE_SECONDARY.name
  val PROP_DOMAIN_OBJECT_PRESENTATION_ID = KEY_DOMAIN_OBJECT_PRESENTATION_ID.name
  val PROP_DOMAIN_OBJECT_ENTITYTYPE = KEY_DOMAIN_OBJECT_ENTITYTYPE.name
  val PROP_DOMAIN_OBJECT_HREF_BASE = KEY_DOMAIN_OBJECT_HREF_BASE.name
}
